channels:
  - conda-forge
  - nodefaults
dependencies:
  - ipykernel
  # Dependencies for VS Code IDE
  - code-server>=3.2
  - jupyter-vscode-proxy
  - openssh
  - rio-tiler
  - pre_commit
  # Upgrade from pangeo-notebook image
  - earthaccess>=0.16.0
  # Pin down to avoid https://github.com/holoviz/pyviz_comms/issues/143
  - pyviz_comms==3.0.4
  - pip
  - pip:
    # Install via pip to avoid conda datafusion/libabseil solver conflicts with py3.12.
    - arbalister
    - jupyter-sshd-proxy
    - jupyterlab-bxplorer
variables:
  TITILER_STAC_ENDPOINT: 'https://openveda.cloud/api/stac'
  TITILER_ENDPOINT: 'https://openveda.cloud/api/raster'
  STAC_CATALOG_NAME: 'VEDA STAC'
  STAC_CATALOG_URL: 'https://openveda.cloud/api/stac'
  STAC_BROWSER_URL: 'https://openveda.cloud/'
